# Generated by Django 5.1.7 on 2025-03-31 04:54

import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(default=exam.models.generate_unique_exam_id, editable=False, max_length=10, unique=True)),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')], max_length=50)),
                ('subject1', models.CharField(max_length=50)),
                ('subject2', models.CharField(blank=True, max_length=50, null=True)),
                ('subject3', models.CharField(blank=True, max_length=50, null=True)),
                ('subject4', models.CharField(blank=True, max_length=50, null=True)),
                ('subject5', models.CharField(blank=True, max_length=50, null=True)),
                ('subject6', models.CharField(blank=True, max_length=50, null=True)),
                ('subject7', models.CharField(blank=True, max_length=50, null=True)),
                ('subject8', models.CharField(blank=True, max_length=50, null=True)),
                ('subject9', models.CharField(blank=True, max_length=50, null=True)),
                ('total_marks', models.CharField(max_length=50)),
            ],
        ),
    ]
