# Generated by Django 5.1.7 on 2025-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exammodel_end_time_exammodel_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='time',
        ),
    ]
