# Generated by Django 5.1.7 on 2025-03-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_exammodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='department',
            field=models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.E', 'Bachelor of Engineering'), ('B.Sc', 'Bachelor of Science'), ('B.Com', 'Bachelor of Commerce'), ('B.A', 'Bachelor of Arts'), ('M.Tech', 'Master of Technology'), ('M.E', 'Master of Engineering'), ('M.Sc', 'Master of Science'), ('M.Com', 'Master of Commerce'), ('M.A', 'Master of Arts'), ('Ph.D', 'Doctor of Philosophy'), ('Diploma', 'Diploma'), ('PG Diploma', 'Post Graduate Diploma'), ('Certificate', 'Certificate')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
