# Generated by Django 5.1.7 on 2025-03-31 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exammodel_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(choices=[(2, '2 - NI-8174')], max_length=50)),
                ('mark_subject1', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject2', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject3', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject4', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject5', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject6', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject7', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject8', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_subject9', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
