# Generated by Django 5.1.7 on 2025-03-31 16:28

import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultmodel',
            name='exam_id',
            field=models.CharField(choices=exam.models.choices_generator, max_length=50),
        ),
    ]
