# Generated by Django 5.1.7 on 2025-03-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_examresultmodel_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresultmodel',
            name='exam_id',
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exammodel'),
        ),
    ]
