# Generated by Django 5.1.7 on 2025-03-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_examresultmodel_exam_id_examresultmodel_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultmodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exammodel'),
        ),
    ]
