# Generated by Django 5.1.7 on 2025-03-29 06:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('AR', 'Ariyalur'), ('CH', 'Chennai'), ('CO', 'Coimbatore'), ('CU', 'Cuddalore'), ('DH', 'Dharmapuri'), ('DI', 'Dindigul'), ('EK', 'Erode'), ('KA', 'Kallakurichi'), ('KA2', 'Kancheepuram'), ('KA3', 'Kanniyakumari'), ('KA4', 'Karur'), ('KR', 'Krishnagiri'), ('MA', 'Madurai'), ('NA', 'Nagapattinam'), ('NI', 'Nilgiris'), ('PE', 'Perambalur'), ('PU', 'Pudukkottai'), ('RA', 'Ramanathapuram'), ('SA', 'Salem'), ('SI', 'Sivaganga'), ('TE', 'Tenkasi'), ('TH', 'Thanjavur'), ('TH2', 'Theni'), ('TH3', 'Thoothukudi'), ('TI', 'Tiruchirappalli'), ('TI2', 'Tirunelveli'), ('TI3', 'Tirupathur'), ('TI4', 'Tiruppur'), ('TI5', 'Tiruvallur'), ('TI6', 'Tiruvannamalai'), ('TV', 'Tiruvarur'), ('VE', 'Vellore'), ('VI', 'Viluppuram'), ('VI2', 'Virudhunagar'), ('AL', 'Alappuzha'), ('ER', 'Ernakulam'), ('ID', 'Idukki'), ('KA', 'Kannur'), ('KA2', 'Kasaragod'), ('KO', 'Kollam'), ('KO2', 'Kottayam'), ('KO3', 'Kozhikode'), ('MA', 'Malappuram'), ('PA', 'Palakkad'), ('PA2', 'Pathanamthitta'), ('TH', 'Thiruvananthapuram'), ('TH2', 'Thrissur'), ('WA', 'Wayanad')], max_length=50)),
                ('state', models.CharField(choices=[('TN', 'Tamil Nadu'), ('KL', 'Kerala')], max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('academic_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('exam_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hostel_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('transport_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('course', models.CharField(choices=[('B.Tech', 'Bachelor of Technology'), ('B.E', 'Bachelor of Engineering'), ('B.Sc', 'Bachelor of Science'), ('B.Com', 'Bachelor of Commerce'), ('B.A', 'Bachelor of Arts'), ('M.Tech', 'Master of Technology'), ('M.E', 'Master of Engineering'), ('M.Sc', 'Master of Science'), ('M.Com', 'Master of Commerce'), ('M.A', 'Master of Arts'), ('Ph.D', 'Doctor of Philosophy'), ('Diploma', 'Diploma'), ('PG Diploma', 'Post Graduate Diploma'), ('Certificate', 'Certificate')], max_length=100)),
                ('semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
