STATE_CHOICES = [
    ("TN", "Tamil Nadu"),
    ("KL", "Kerala"),
]

DISTRICT_CHOICES = [
    # Tamil Nadu Districts
    ("AR", "Ariyalur"),
    ("CH", "Chennai"),
    ("CO", "Coimbatore"),
    ("CU", "Cuddalore"),
    ("DH", "Dharmapuri"),
    ("DI", "Dindigul"),
    ("EK", "Erode"),
    ("KA", "Kallakurichi"),
    ("KA2", "Kancheepuram"),
    ("KA3", "Kanniyakumari"),
    ("KA4", "Karur"),
    ("KR", "Krishnagiri"),
    ("MA", "Madurai"),
    ("NA", "Nagapattinam"),
    ("NI", "Nilgiris"),
    ("PE", "Perambalur"),
    ("PU", "Pudukkottai"),
    ("RA", "Ramanathapuram"),
    ("SA", "Salem"),
    ("SI", "Sivaganga"),
    ("TE", "Tenkasi"),
    ("TH", "Thanjavur"),
    ("TH2", "Theni"),
    ("TH3", "Thoothukudi"),
    ("TI", "Tiruchirappalli"),
    ("TI2", "Tirunelveli"),
    ("TI3", "Tirupathur"),
    ("TI4", "Tiruppur"),
    ("TI5", "Tiruvallur"),
    ("TI6", "Tiruvannamalai"),
    ("TV", "Tiruvarur"),
    ("VE", "Vellore"),
    ("VI", "Viluppuram"),
    ("VI2", "Virudhunagar"),

    # Kerala Districts
    ("AL", "Alappuzha"),
    ("ER", "Ernakulam"),
    ("ID", "Idukki"),
    ("KA", "Kannur"),
    ("KA2", "Kasaragod"),
    ("KO", "Kollam"),
    ("KO2", "Kottayam"),
    ("KO3", "Kozhikode"),
    ("MA", "Malappuram"),
    ("PA", "Palakkad"),
    ("PA2", "Pathanamthitta"),
    ("TH", "Thiruvananthapuram"),
    ("TH2", "Thrissur"),
    ("WA", "Wayanad"),
]

COURSE_CHOICES = [
    ("B.Tech", "Bachelor of Technology"),
    ("B.E", "Bachelor of Engineering"),
    ("B.Sc", "Bachelor of Science"),
    ("B.Com", "Bachelor of Commerce"),
    ("B.A", "Bachelor of Arts"),
    ("M.Tech", "Master of Technology"),
    ("M.E", "Master of Engineering"),
    ("M.Sc", "Master of Science"),
    ("M.Com", "Master of Commerce"),
    ("M.A", "Master of Arts"),
    ("Ph.D", "Doctor of Philosophy"),
    ("Diploma", "Diploma"),
    ("PG Diploma", "Post Graduate Diploma"),
    ("Certificate", "Certificate"),
]

SEMESTER_CHOICES = [
    ("1", "First"),
    ("2", "Second"),
    ("3", "Third"),
    ("4", "Fourth"),
    ("5", "Fifth"),
    ("6", "Sixth"),
    ("7", "Seventh"),
    ("8", "Eighth"),
]