# Generated by Django 5.1.7 on 2025-04-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_coverage', models.CharField(choices=[('below_30', 'Below 30%'), ('30_54', '30 to 54%'), ('55_69', '55 to 69%'), ('70_84', '70 to 84%'), ('85_100', '85 to 100%')], max_length=50)),
                ('teacher_preparation', models.CharField(choices=[('not_at_all', 'Won’t teach at all'), ('indifferent', 'Indifferently'), ('poor', 'Poorly'), ('satisfactory', 'Satisfactorily'), ('thorough', 'Thoroughly')], max_length=50)),
                ('teacher_communication', models.CharField(choices=[('very_poor', 'Very poor communication'), ('ineffective', 'Generally ineffective'), ('satisfactory', 'Just satisfactorily'), ('sometimes_effective', 'Sometimes effective'), ('always_effective', 'Always effective')], max_length=50)),
                ('teaching_approach', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very good'), ('excellent', 'Excellent')], max_length=50)),
                ('evaluation_fairness', models.CharField(choices=[('unfair', 'Unfair'), ('usually_unfair', 'Usually unfair'), ('sometimes_unfair', 'Sometimes unfair'), ('usually_fair', 'Usually fair'), ('always_fair', 'Always fair')], max_length=50)),
                ('assignment_discussion', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Occasionally/Sometimes'), ('usually', 'Usually'), ('every_time', 'Every time')], max_length=50)),
                ('internship_opportunities', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('regularly', 'Regularly')], max_length=50)),
                ('mentoring_effectiveness', models.CharField(choices=[('not_at_all', 'Not at all'), ('marginally', 'Marginally'), ('moderately', 'Moderately'), ('very_well', 'Very well'), ('significantly', 'Significantly')], max_length=50)),
                ('learning_opportunities', models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree')], max_length=50)),
                ('competency_info', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Occasionally/Sometimes'), ('usually', 'Usually'), ('every_time', 'Every time')], max_length=50)),
                ('mentor_followup', models.CharField(choices=[('no_mentor', 'I don’t have a mentor'), ('rarely', 'Rarely'), ('sometimes', 'Occasionally/Sometimes'), ('usually', 'Usually'), ('every_time', 'Every time')], max_length=50)),
                ('teaching_examples', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Occasionally/Sometimes'), ('usually', 'Usually'), ('every_time', 'Every time')], max_length=50)),
                ('strength_identification', models.CharField(choices=[('unable', 'Unable to'), ('slightly', 'Slightly'), ('partially', 'Partially'), ('reasonably', 'Reasonably'), ('fully', 'Fully')], max_length=50)),
                ('weakness_help', models.CharField(choices=[('never', 'Never'), ('rarely', 'Rarely'), ('sometimes', 'Occasionally/Sometimes'), ('usually', 'Usually'), ('every_time', 'Every time')], max_length=50)),
                ('student_engagement', models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree')], max_length=50)),
                ('student_centric_methods', models.CharField(choices=[('not_at_all', 'Not at all'), ('very_little', 'Very little'), ('somewhat', 'Somewhat'), ('moderate', 'Moderate'), ('great_extent', 'To a great extent')], max_length=50)),
                ('extracurricular', models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree')], max_length=50)),
                ('soft_skills', models.CharField(choices=[('not_at_all', 'Not at all'), ('very_little', 'Very little'), ('somewhat', 'Somewhat'), ('moderate', 'Moderate'), ('great_extent', 'To a great extent')], max_length=50)),
                ('ict_usage', models.CharField(choices=[('below_29', 'Below 29%'), ('30_49', '30 – 49%'), ('50_69', '50 – 69%'), ('70_89', '70 – 89%'), ('above_90', 'Above 90%')], max_length=50)),
                ('overall_quality', models.CharField(choices=[('strongly_disagree', 'Strongly disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly agree')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
