# Generated by Django 5.1.7 on 2025-04-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='principal_quality',
            field=models.CharField(choices=[('not_at_all', 'Not at all'), ('very_little', 'Very little'), ('somewhat', 'Somewhat'), ('moderate', 'Moderate'), ('great_extent', 'To a great extent')], default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
