# Generated by Django 5.1.7 on 2025-04-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_surveyresponse_principal_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='principal_quality',
            field=models.CharField(blank=True, choices=[('not_at_all', 'Not at all'), ('very_little', 'Very little'), ('somewhat', 'Somewhat'), ('moderate', 'Moderate'), ('great_extent', 'To a great extent')], max_length=50, null=True),
        ),
    ]
