name: Django CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: python my_script.py
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./web/requirements.txt
    - name: run server
      run: |
        python ./web/manage.py runserver
